-- AlterTable
ALTER TABLE "Recipe" ADD COLUMN     "authorId" INTEGER NOT NULL DEFAULT 29;

-- AddForeignKey
ALTER TABLE "Recipe" ADD CONSTRAINT "Recipe_authorId_fkey" FOREIGN KEY ("authorId") REFERENCES "User"("id") ON DELETE RESTRICT ON UPDATE CASCADE;
